[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[project]
name = "utils_zp"
version = "2.0.0"
description = "Utilities of zp"
readme = "README.md"
requires-python = ">=3.10"
authors = [
    { name = "Zhipang Wang", email = "zhipangwang@gmail.com" }
]
dependencies = [
    "nvidia-ml-py",
    "PyYAML",
    "tqdm",
]

[project.scripts]
zp = "utils_zp.cli.main:main"
zpbashrc = "utils_zp.cli.zpbashrc:main"
zpburn = "utils_zp.cli.zpburn:main"
zpckpt = "utils_zp.cli.zpckpt:main"
zpdata = "utils_zp.cli.zpdata:main"
zpexp = "utils_zp.cli.zpexp:main"
zpjobs = "utils_zp.cli.zpjobs:main"
zppshell = "utils_zp.cli.zppshell:main"
zppremodel = "utils_zp.cli.zppremodel:main"
zppremodels = "utils_zp.cli.zppremodel:main"
zprules = "utils_zp.cli.zprules:main"

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]
