# FROM tsqb_frontend_image:env
# FROM gradio-app:env
FROM tsqb:env 

RUN mkdir -p /usr/src/app/TSQB_System
WORKDIR /usr/src/app/TSQB_System
COPY data/final_scenario.json data/final_scenario.json
COPY docker docker
COPY figs figs
COPY src src
COPY requirements.txt requirements.txt

COPY database database
COPY database_old database_old
COPY prompts prompts

ENV GRADIO_SERVER_NAME="0.0.0.0"
# CMD python src/main_v2_1_3.py --address 0.0.0.0 --port 8601
CMD python src/app.py --address 0.0.0.0 --port 8601
# CMD python src/main_app_test.py
#  --address 0.0.0.0 --port 8601
EXPOSE 8601


# sudo docker build -f docker/dockerfile -t tsqb_frontend_image .

# sudo docker run -d --name tsqb_frontend -p 8005:8005 tsqb_frontend_image:latest
# sudo docker run -v /path/on/database:/app/database -v /path/on/database:/app/database -d --name tsqb_frontend -p 8005:8005 tsqb_frontend_image:latest  # database, prompt
# sudo docker logs -f tsqb_frontend
