FROM python:3.8-slim
# FROM python:3.10.14

RUN pip install gradio
RUN pip install func_timeout
RUN pip install openpyxl

# sudo docker build -f docker/dockerfile.env -t tsqb_frontend_image:env .

## 需要添加包 openpyxl